# Generated by Django 6.0.8 on 2026-09-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecall',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['active', 'available'], name='portal_menu_active_abcba8_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'active'], name='portal_menu_categor_19dac8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecall',
            index=models.Index(fields=['status', '-created_at'], name='portal_serv_status_8f4877_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecall',
            index=models.Index(fields=['table_number', 'status'], name='portal_serv_table_n_a4d3d6_idx'),
        ),
    ]
