# Generated by Django 6.0.8 on 2026-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_servicecall_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
