# Generated by Django 6.0.8 on 2026-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_tableqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_portal_url', models.URLField(help_text='Example: https://yourusername.pythonanywhere.com', max_length=500)),
                ('qr_title', models.CharField(default='Group of BBN Coastal Pearl Samudrathali', max_length=200)),
                ('qr_message', models.CharField(default='Digital Menu - "Scan QR and check our menu"', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Settings',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
    ]
